### ISSUE TITLE
hmac_sha256 incorrect

### ISSUE THREAD

**Issue by Cyvadra** [JuliaCrypto/SHA.jl#63]
```

julia> tmp_key = rand(UInt8,16);

julia> str = "123";

julia> bytes2hex( SHA.hmac_sha256(tmp_key,str) )
"ce0006ef9b02c5c710b8bfcb47e6f5177b44323992e2918dfbdb087a03ec6f4f"

julia> bytes2hex(tmp_key)
"e85726cc1b12609bbaebe535f0926f59"

```

where the correct answer should be "917ca2bb41787aadb5384038f2790b6e0a02e058593e37e1297f970be269e583" using other methods.. (ref:https://www.freeformatter.com/hmac-generator.html)
julia version v1.4.1, tried other strings and found the result incorrect..
@staticfloat

**Comment by staticfloat** [comment]
The correct answer to this particular example is `ce0006ef9b02c5c710b8bfcb47e6f5177b44323992e2918dfbdb087a03ec6f4f`.  The issue here is that you are not feeding `tmp_key` to the other tools you're checking against, you're feeding `bytes2hex(tmp_key)`, they're not the same thing.  The online tool that you posted is not interpreting the key as hex, it's reading the UTF-8 input bytes and using those binary representations.

If you want to do that, use `hmac_sha256(collect(codeunits(tmp_key)), str)` instead of `hmac_sha256(tmp_key, str)`.

To double-check, use an online tool such as https://www.liavaag.org/English/SHA-Generator/HMAC/ and use `Key type: HEX` with the key `e85726cc1b12609bbaebe535f0926f59`.

**Comment by pankgeorg** [comment]
Nonetheless, this issue is the closest thing to hmac_sha256 documentation I've found. Thanks for the reply!
